### ISSUE TITLE
Request - Breath of the wild Paraglider 1.10.2 and more

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ganondorf629/zeldamobs#3]
Zelda Mobs for 1.10.2 need the following to be Zelda
Botw Paraglider
Twilight princess hookshot
Hylian Shield
Octorocks
Stalchild Night*

**Comment by Ganondorf629** [comment]
I'll take a look on it :)

**Comment by Ganondorf629** [comment]
Hylian Shield has been added :)

Next feature: Hookshot
