### ISSUE TITLE
Helmaroc king spawn everywhere ([1.11.2] Zelda Mobs v1.5.5)

### ISSUE THREAD

**Issue by Lightone** [Ganondorf629/zeldamobs#7]
some time with pacific mode activated the life bar appear  O_O and see the four life bar but dont see any king xD near 

![2017-04-12_23 32 31](https://cloud.githubusercontent.com/assets/2113099/24990625/fd26fb5c-1fda-11e7-91f2-93de9425721f.png)

**Comment by Ganondorf629** [comment]
You are using v1.5.5, which is an alpha. It's a known bug that has been fixed in v1.6
