### ISSUE TITLE
1.10.2 - Load time slowed because of missing models

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [Ganondorf629/zeldamobs#8]
https://pastebin.com/HqjSHjc8

Consol spams these, when these are spammed it slows the loadtime.

**Comment by Ganondorf629** [comment]
You should upgrade to 1.11.2, as long as I've not planned to update the 1.10.2 version, all the new features/improvements are on the 1.11.2 version, and everything is fine there

**Comment by EPIICTHUNDERCAT** [comment]
yea, I removed it since I thought that may be the case. Cant move to 1.11.2 beause this pack was requested for 1.10.2! no can do
